### ISSUE TITLE
Add new textures

### ISSUE THREAD

**Issue by Vap0r1ze** [destruc7i0n/minecraft-textures#10]
After [1.14](https://minecraft.gamepedia.com/Texture_Update) many textures were updated, I'd like to see this repo include those.

**Comment by Vap0r1ze** [comment]
If you want to, you can use all of [these](https://github.com/Vap0r1ze/minecraft-icons) I just rendered

**Comment by destruc7i0n** [comment]
This has been something I've considered for a while, I just have not found the time to re-create the list.
 What did you use to make those images? The images I use are only 32x32 to try and make the bundle smaller... The sizes rendered there are pretty large

**Comment by Vap0r1ze** [comment]
> What did you use to make those images?

I used the [BlockRenderer](https://www.curseforge.com/minecraft/mc-mods/blockrenderer) mod

> The images I use are only 32x32 to try and make the bundle smaller... The sizes rendered there are pretty large

It would be pretty easy to do this with ffmpeg
```bash
mkdir -p assets-resized
cd assets
for f in *.png; do
  ffmpeg -i "$f" -vf scale=32:32:flags=neighbor ../assets-resized/$f
done
```

**Comment by destruc7i0n** [comment]
Updated in latest version.
