### ISSUE TITLE
Textures are 32x32

### ISSUE THREAD

**Issue by colecrouter** [destruc7i0n/minecraft-textures#11]
I'm guessing there's a reason behind it, Otherwise I'd PR to make the package smaller.

I'm trying to bundle this package into a serverless website, but it's too large (>1mb). I have to load it from unpkg, but this means I can't compile it in any way, so every visitor has to download all 1000+ textures on every non-cached page load. My hope would be to get the JSON down to ~1/3 size, so can I bundle it.

**Comment by destruc7i0n** [comment]
This decision was made because the primary use case of this package is my [crafting generator](https://crafting.thedestruc7i0n.ca/) and it looked best with the level of detail in 32x32 than 16x16. I wanted to replicate the look of Java as closely as possible.

**Comment by colecrouter** [comment]
Understandable. I made a script to resize the images, so that fits my case at least. I now see that the 16x16 block models look a little... classic.
