### ISSUE TITLE
Duplicate entries in json files

### ISSUE THREAD

**Issue by mainrs** [destruc7i0n/minecraft-textures#9]
The following entries are listed multiple times inside the json file for version 1.6.2:
- brewing_stand
- flower_pot
- wheat
- sugar_cane
- nether_wart
- cauldron
- dead_horn_coral_fan

**Comment by mainrs** [comment]
These two `jq` commands might come in handy:
```
$ jq -r '.items | unique_by({id}) | length' 1.16.json
975
$ jq -r '.items |  length' 1.16.json
982
```

**Comment by destruc7i0n** [comment]
Thanks for the report! I was apparently not watching this repo so I never got notified 🤔 
I've fixed this and even added a github workflow to check. Hopefully it should not happen again and be there for how long it was 😅
